# config.toml
app_name = "DeepDoc"
debug = true

[server]
port = 8080
host = "localhost"

[database]
pg_host = "127.0.0.1"
pg_port = 12345
pg_user_name = "xxx"
pg_password = "xxx"
pg_db_name = "miner"
mysql_host = "127.0.0.1"
mysql_port = 3306
mysql_user_name = "admin"
mysql_password = "plano4628"
mysql_db_name = "miner"
max_connections = 10
table_name_login_sessions = "login_sessions"
database_type = "mysql"

[auth]
jwt_secret = "super-secret-key"
session_duration_hours = 24
